"use client";

import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { Provider } from "react-redux";

import { store } from "@/store";
import lightTheme from "@/styles/themes/lightTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sample OpenAI Integration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <ThemeProvider theme={lightTheme}>
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </Provider>
    </html>
  );
}
